/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AttachmentFile {
        "accepts": string;
        "download": string;
        "filename": string;
        "filetype": string;
        "href": string;
        "max": number;
        "name": string;
        /**
          * @default 100
         */
        "percent": number;
        /**
          * @default true
         */
        "preview": boolean;
        "size": number;
        "src": string;
        /**
          * @default "complete"
         */
        "state": string;
        "url": string;
        "validationMessage": string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AttachmentPreview {
        "filetype": string;
        "src": string;
    }
    interface InputAttachment {
        "accepts": string;
        "directupload": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "max": number;
        /**
          * @default false
         */
        "multiple": boolean;
        "name": string;
        /**
          * @default true
         */
        "preview": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default true
         */
        "uploadDialog": boolean;
    }
    interface UploadDialog {
        "addUpload": (id: string, filename: string) => Promise<void>;
        "close": () => Promise<void>;
        "completeUpload": (id: string) => Promise<void>;
        "open": () => Promise<void>;
        "removeUpload": (id: string) => Promise<void>;
        "setError": (id: string, error: string) => Promise<void>;
        "startUpload": (id: string) => Promise<void>;
        "updateProgress": (id: string, percent: number) => Promise<void>;
    }
}
export interface AttachmentFileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAttachmentFileElement;
}
declare global {
    interface HTMLAttachmentFileElementEventMap {
        "attachment-file:remove": any;
        "attachment-file:validation": any;
        "attachment-file:ready": any;
    }
    interface HTMLAttachmentFileElement extends Components.AttachmentFile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAttachmentFileElementEventMap>(type: K, listener: (this: HTMLAttachmentFileElement, ev: AttachmentFileCustomEvent<HTMLAttachmentFileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAttachmentFileElementEventMap>(type: K, listener: (this: HTMLAttachmentFileElement, ev: AttachmentFileCustomEvent<HTMLAttachmentFileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAttachmentFileElement: {
        prototype: HTMLAttachmentFileElement;
        new (): HTMLAttachmentFileElement;
    };
    interface HTMLAttachmentPreviewElement extends Components.AttachmentPreview, HTMLStencilElement {
    }
    var HTMLAttachmentPreviewElement: {
        prototype: HTMLAttachmentPreviewElement;
        new (): HTMLAttachmentPreviewElement;
    };
    interface HTMLInputAttachmentElement extends Components.InputAttachment, HTMLStencilElement {
    }
    var HTMLInputAttachmentElement: {
        prototype: HTMLInputAttachmentElement;
        new (): HTMLInputAttachmentElement;
    };
    interface HTMLUploadDialogElement extends Components.UploadDialog, HTMLStencilElement {
    }
    var HTMLUploadDialogElement: {
        prototype: HTMLUploadDialogElement;
        new (): HTMLUploadDialogElement;
    };
    interface HTMLElementTagNameMap {
        "attachment-file": HTMLAttachmentFileElement;
        "attachment-preview": HTMLAttachmentPreviewElement;
        "input-attachment": HTMLInputAttachmentElement;
        "upload-dialog": HTMLUploadDialogElement;
    }
}
declare namespace LocalJSX {
    interface AttachmentFile {
        "accepts"?: string;
        "download"?: string;
        "filename"?: string;
        "filetype"?: string;
        "href"?: string;
        "max"?: number;
        "name"?: string;
        "onAttachment-file:ready"?: (event: AttachmentFileCustomEvent<any>) => void;
        "onAttachment-file:remove"?: (event: AttachmentFileCustomEvent<any>) => void;
        "onAttachment-file:validation"?: (event: AttachmentFileCustomEvent<any>) => void;
        /**
          * @default 100
         */
        "percent"?: number;
        /**
          * @default true
         */
        "preview"?: boolean;
        "size"?: number;
        "src"?: string;
        /**
          * @default "complete"
         */
        "state"?: string;
        "url"?: string;
        "validationMessage"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AttachmentPreview {
        "filetype"?: string;
        "src"?: string;
    }
    interface InputAttachment {
        "accepts"?: string;
        "directupload"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "max"?: number;
        /**
          * @default false
         */
        "multiple"?: boolean;
        "name"?: string;
        /**
          * @default true
         */
        "preview"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default true
         */
        "uploadDialog"?: boolean;
    }
    interface UploadDialog {
    }

    interface AttachmentFileAttributes {
        "name": string;
        "accepts": string;
        "max": number;
        "url": string;
        "value": string;
        "filename": string;
        "src": string;
        "href": string;
        "download": string;
        "filetype": string;
        "size": number;
        "state": string;
        "percent": number;
        "preview": boolean;
        "validationMessage": string;
    }
    interface AttachmentPreviewAttributes {
        "src": string;
        "filetype": string;
    }
    interface InputAttachmentAttributes {
        "name": string;
        "directupload": string;
        "multiple": boolean;
        "required": boolean;
        "accepts": string;
        "max": number;
        "preview": boolean;
        "disabled": boolean;
        "uploadDialog": boolean;
    }

    interface IntrinsicElements {
        "attachment-file": Omit<AttachmentFile, keyof AttachmentFileAttributes> & { [K in keyof AttachmentFile & keyof AttachmentFileAttributes]?: AttachmentFile[K] } & { [K in keyof AttachmentFile & keyof AttachmentFileAttributes as `attr:${K}`]?: AttachmentFileAttributes[K] } & { [K in keyof AttachmentFile & keyof AttachmentFileAttributes as `prop:${K}`]?: AttachmentFile[K] };
        "attachment-preview": Omit<AttachmentPreview, keyof AttachmentPreviewAttributes> & { [K in keyof AttachmentPreview & keyof AttachmentPreviewAttributes]?: AttachmentPreview[K] } & { [K in keyof AttachmentPreview & keyof AttachmentPreviewAttributes as `attr:${K}`]?: AttachmentPreviewAttributes[K] } & { [K in keyof AttachmentPreview & keyof AttachmentPreviewAttributes as `prop:${K}`]?: AttachmentPreview[K] };
        "input-attachment": Omit<InputAttachment, keyof InputAttachmentAttributes> & { [K in keyof InputAttachment & keyof InputAttachmentAttributes]?: InputAttachment[K] } & { [K in keyof InputAttachment & keyof InputAttachmentAttributes as `attr:${K}`]?: InputAttachmentAttributes[K] } & { [K in keyof InputAttachment & keyof InputAttachmentAttributes as `prop:${K}`]?: InputAttachment[K] };
        "upload-dialog": UploadDialog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "attachment-file": LocalJSX.IntrinsicElements["attachment-file"] & JSXBase.HTMLAttributes<HTMLAttachmentFileElement>;
            "attachment-preview": LocalJSX.IntrinsicElements["attachment-preview"] & JSXBase.HTMLAttributes<HTMLAttachmentPreviewElement>;
            "input-attachment": LocalJSX.IntrinsicElements["input-attachment"] & JSXBase.HTMLAttributes<HTMLInputAttachmentElement>;
            "upload-dialog": LocalJSX.IntrinsicElements["upload-dialog"] & JSXBase.HTMLAttributes<HTMLUploadDialogElement>;
        }
    }
}
